#!/bin/sh
# wait-for - Wait for a service to be ready

set -e

host="$1"
shift
cmd="$@"

echo "Waiting for $host to be ready..."

until nc -z "$host" 5432; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

>&2 echo "Postgres is up - executing command"
exec $cmd
